server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
        - id: user
          uri:  lb://user
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: order
          uri:  lb://order
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/restaurant-service/**
          filters:
            - StripPrefix=1
        - id: driver
          uri: lb://driver
          predicates:
            - Path=/driver-service/**
          filters:
            - StripPrefix=1
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1

info:
  app:
    name: ${spring.application.name}


eureka:
  client:
    service-url:
      defaultZone: {EUREKA_SERVER: http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info